import time
import os
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


def update_cookies_file(output_file="cookies.txt"):
    """
    브라우저를 열어 사용자가 로그인하게 한 뒤,
    쿠키를 추출하여 Netscape 포맷(cookies.txt)으로 저장합니다.
    """
    print("=" * 60)
    print("🔐 유튜브 로그인 도구 (Selenium)")
    print("   1. 브라우저가 열리면 '깡통 계정'으로 로그인하세요.")
    print("   2. 로그인이 완료되면 프로그램이 자동으로 감지하고 창을 닫습니다.")
    print("=" * 60)

    # 1. 브라우저 옵션 설정 (봇 탐지 최소화)
    options = webdriver.ChromeOptions()
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)

    # 2. 브라우저 실행
    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)

    try:
        driver.get("https://www.youtube.com")
        print("⏳ 로그인 대기 중... (브라우저에서 로그인을 진행해주세요)")

        # 3. 로그인 감지 루프
        while True:
            cookies = driver.get_cookies()
            # 'LOGIN_INFO' 쿠키가 생기면 로그인된 것으로 판단
            is_logged_in = any(cookie['name'] == 'LOGIN_INFO' for cookie in cookies)

            if is_logged_in:
                print("✅ 로그인 감지됨! 3초 후 쿠키를 저장합니다...")
                time.sleep(3)  # 쿠키가 완전히 세팅되도록 잠시 대기
                break

            time.sleep(2)

        # 4. Netscape 포맷으로 변환하여 저장
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by login_helper.py\n\n")

            for cookie in driver.get_cookies():
                # Netscape 포맷: domain flag path secure expiration name value
                domain = cookie.get('domain', '')
                # 도메인이 .으로 시작하면 TRUE, 아니면 FALSE
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure') else 'FALSE'
                # 만료시간이 없으면 1년 뒤로 설정
                expiration = int(cookie.get('expiry', time.time() + 3600 * 24 * 365))
                name = cookie.get('name', '')
                value = cookie.get('value', '')

                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

        print(f"📂 쿠키 파일 생성 완료: {os.path.abspath(output_file)}")

    except Exception as e:
        print(f"❌ 오류 발생: {e}")
    finally:
        driver.quit()


if __name__ == "__main__":
    update_cookies_file()