# 차단 방지용

import os
import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager


class CookieManager:
    def __init__(self):
        # 프로젝트 최상위 폴더 경로 찾기
        current_dir = os.path.dirname(os.path.abspath(__file__))  # Detour 폴더
        self.project_root = os.path.dirname(os.path.dirname(current_dir))  # shortMaker 폴더
        self.cookie_filename = "cookies.txt"
        self.cookie_path = os.path.join(self.project_root, self.cookie_filename)

    def get_cookie_path(self):
        """
        쿠키 파일 경로를 반환합니다.
        파일이 없으면 -> 자동으로 브라우저를 띄워 로그인을 유도하고 파일을 생성합니다.
        """
        if os.path.exists(self.cookie_path):
            # 1. 이미 쿠키가 있는 경우
            # print(f"🍪 [Cookie] 기존 쿠키 사용: {self.cookie_path}")
            return self.cookie_path
        else:
            # 2. 쿠키가 없는 경우 -> 봇 실행
            print(f"⚠️ [Cookie] 쿠키 파일이 없습니다. 새 로그인이 필요합니다.")
            success = self._run_selenium_login()

            if success:
                return self.cookie_path
            else:
                return None

    def _run_selenium_login(self):
        """
        (내부 함수) 셀레니움 브라우저를 띄워 쿠키를 추출합니다.
        """
        print("🤖 [Bot] 로그인 봇을 실행합니다...")
        print("🚀 [필수] 브라우저가 뜨면 60초 안에 '구글 로그인'을 완료해주세요!")

        options = Options()
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_argument(
            "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

        try:
            driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
            driver.get("https://www.youtube.com")

            # 60초 카운트다운 (로그인 대기)
            for i in range(60, 0, -1):
                print(f"\r⏳ 로그인 대기 중... {i}초 남음 ", end="")
                time.sleep(1)
            print("\n🤖 [Bot] 쿠키 추출 중...")

            selenium_cookies = driver.get_cookies()

            # Netscape 포맷으로 저장
            with open(self.cookie_path, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# Generated by ShortMaker\n\n")

                for cookie in selenium_cookies:
                    domain = cookie.get('domain', '')
                    domain_specified = "TRUE" if domain.startswith('.') else "FALSE"
                    path = cookie.get('path', '/')
                    secure = "TRUE" if cookie.get('secure') else "FALSE"
                    expires = int(cookie.get('expiry', time.time() + 3600 * 24 * 365))
                    name = cookie.get('name', '')
                    value = cookie.get('value', '')

                    f.write(f"{domain}\t{domain_specified}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

            print(f"\n✅ [성공] 쿠키 저장 완료: {self.cookie_path}")
            driver.quit()
            return True

        except Exception as e:
            print(f"\n❌ [오류] 봇 실행 실패: {e}")
            try:
                driver.quit()
            except:
                pass
            return False